version: "3"

networks:
  universitymvp:
    external:
      name: universitymvp

services:
  cliPhysics:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    environment:
      - SYS_CHANNEL=system-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/universitymvp.com/orderers/orderer.universitymvp.com/msp/tlscacerts/tlsca.universitymvp.com-cert.pem
      # - FABRIC_LOGGING_SPEC=INFO
      - CC_PATH=/opt/gopath/src/github.com/chaincode
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=universitymvp
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.physics.universitymvp.com:7051
      - CORE_PEER_LOCALMSPID=PhysicsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/physics.universitymvp.com/peers/peer0.physics.universitymvp.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/physics.universitymvp.com/peers/peer0.physics.universitymvp.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/physics.universitymvp.com/peers/peer0.physics.universitymvp.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/physics.universitymvp.com/users/Admin@physics.universitymvp.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/chaincode/:/opt/gopath/src/github.com/chaincode
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts

    networks:
      universitymvp:
        aliases:
          - cliPhysics.universitymvp.com

  cliMaths:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.labels.name == worker1
    environment:
      - SYS_CHANNEL=system-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/universitymvp.com/orderers/orderer.universitymvp.com/msp/tlscacerts/tlsca.universitymvp.com-cert.pem
      # - FABRIC_LOGGING_SPEC=INFO
      - CC_PATH=/opt/gopath/src/github.com/chaincode
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=universitymvp
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.maths.universitymvp.com:9051
      - CORE_PEER_LOCALMSPID=MathsMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/maths.universitymvp.com/peers/peer0.maths.universitymvp.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/maths.universitymvp.com/peers/peer0.maths.universitymvp.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/maths.universitymvp.com/peers/peer0.maths.universitymvp.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/maths.universitymvp.com/users/Admin@maths.universitymvp.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/chaincode/:/opt/gopath/src/github.com/chaincode
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      universitymvp:
        aliases:
          - cliMaths.universitymvp.com

  cliChemistry:
    container_name: cli
    image: hyperledger/fabric-tools:2.3
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.labels.name == worker2
    environment:
      - SYS_CHANNEL=system-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/ordererOrganizations/universitymvp.com/orderers/orderer.universitymvp.com/msp/tlscacerts/tlsca.universitymvp.com-cert.pem
      # - FABRIC_LOGGING_SPEC=INFO
      - CC_PATH=/opt/gopath/src/github.com/chaincode
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=universitymvp
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.chemistry.universitymvp.com:11051
      - CORE_PEER_LOCALMSPID=ChemistryMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/chemistry.universitymvp.com/peers/peer0.chemistry.universitymvp.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/chemistry.universitymvp.com/peers/peer0.chemistry.universitymvp.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/chemistry.universitymvp.com/peers/peer0.chemistry.universitymvp.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/peerOrganizations/chemistry.universitymvp.com/users/Admin@chemistry.universitymvp.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/chaincode/:/opt/gopath/src/github.com/chaincode
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations:/opt/gopath/src/github.com/hyperledger/fabric/peer/organizations/
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      universitymvp:
        aliases:
          - cliChemistry.universitymvp.com
