# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3"

volumes:
  ordereruniversitymvpcom:
  orderer2universitymvpcom:
  orderer3universitymvpcom:
  orderer4universitymvpcom:
  orderer5universitymvpcom:
  peer0physicsuniversitymvpcom:
  peer0mathsuniversitymvpcom:
  peer0chemistryuniversitymvpcom:

networks:
  universitymvp:
    external:
      name: universitymvp

services:
  ordereruniversitymvpcom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer.universitymvp.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer.universitymvp.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer.universitymvp.com/tls/:/var/hyperledger/orderer/tls
      - ordereruniversitymvpcom:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    networks:
      universitymvp:
        aliases:
          - orderer.universitymvp.com
  orderer2universitymvpcom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer2.universitymvp.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer2.universitymvp.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer2.universitymvp.com/tls/:/var/hyperledger/orderer/tls
      - orderer2universitymvpcom:/var/hyperledger/production/orderer
    ports:
      - 8050:7050
    networks:
      universitymvp:
        aliases:
          - orderer2.universitymvp.com

  orderer3universitymvpcom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer3.universitymvp.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer3.universitymvp.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer3.universitymvp.com/tls/:/var/hyperledger/orderer/tls
      - orderer3universitymvpcom:/var/hyperledger/production/orderer
    ports:
      - 9050:7050
    networks:
      universitymvp:
        aliases:
          - orderer3.universitymvp.com

  orderer4universitymvpcom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer4.universitymvp.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer4.universitymvp.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer4.universitymvp.com/tls/:/var/hyperledger/orderer/tls
      - orderer4universitymvpcom:/var/hyperledger/production/orderer
    ports:
      - 10050:7050
    networks:
      universitymvp:
        aliases:
          - orderer4.universitymvp.com

  orderer5universitymvpcom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: orderer5.universitymvp.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/system-genesis-block/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer5.universitymvp.com/msp:/var/hyperledger/orderer/msp
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/ordererOrganizations/universitymvp.com/orderers/orderer5.universitymvp.com/tls/:/var/hyperledger/orderer/tls
      - orderer5universitymvpcom:/var/hyperledger/production/orderer
    ports:
      - 11050:7050
    networks:
      universitymvp:
        aliases:
          - orderer5.universitymvp.com

  peer0physicsuniversitymvpcom:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: peer0.physics.universitymvp.com
    image: hyperledger/fabric-peer:2.3
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=universitymvp
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.physics.universitymvp.com
      - CORE_PEER_ADDRESS=peer0.physics.universitymvp.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.physics.universitymvp.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.physics.universitymvp.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.physics.universitymvp.com:7051
      - CORE_PEER_LOCALMSPID=PhysicsMSP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/peerOrganizations/physics.universitymvp.com/peers/peer0.physics.universitymvp.com/msp:/etc/hyperledger/fabric/msp
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/peerOrganizations/physics.universitymvp.com/peers/peer0.physics.universitymvp.com/tls:/etc/hyperledger/fabric/tls
      - peer0physicsuniversitymvpcom:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      universitymvp:
        aliases:
          - peer0.physics.universitymvp.com

  peer0mathsuniversitymvpcom:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker1
    container_name: peer0.maths.universitymvp.com
    image: hyperledger/fabric-peer:2.3
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=universitymvp
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.maths.universitymvp.com
      - CORE_PEER_ADDRESS=peer0.maths.universitymvp.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.maths.universitymvp.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.maths.universitymvp.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.maths.universitymvp.com:9051
      - CORE_PEER_LOCALMSPID=MathsMSP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/peerOrganizations/maths.universitymvp.com/peers/peer0.maths.universitymvp.com/msp:/etc/hyperledger/fabric/msp
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/peerOrganizations/maths.universitymvp.com/peers/peer0.maths.universitymvp.com/tls:/etc/hyperledger/fabric/tls
      - peer0mathsuniversitymvpcom:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 9051:9051
    networks:
      universitymvp:
        aliases:
          - peer0.maths.universitymvp.com

  peer0chemistryuniversitymvpcom:
    deploy:
      placement:
        constraints:
          - node.labels.name == worker2
    container_name: peer0.chemistry.universitymvp.com
    image: hyperledger/fabric-peer:2.3
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=universitymvp
      - FABRIC_LOGGING_SPEC=INFO
      #- FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      # Peer specific variabes
      - CORE_PEER_ID=peer0.chemistry.universitymvp.com
      - CORE_PEER_ADDRESS=peer0.chemistry.universitymvp.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.chemistry.universitymvp.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.chemistry.universitymvp.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.chemistry.universitymvp.com:11051
      - CORE_PEER_LOCALMSPID=ChemistryMSP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
    volumes:
      - /var/run/:/host/var/run/
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/peerOrganizations/chemistry.universitymvp.com/peers/peer0.chemistry.universitymvp.com/msp:/etc/hyperledger/fabric/msp
      - /home/ubuntu/hlf-docker-swarm/universitymvp-network/organizations/peerOrganizations/chemistry.universitymvp.com/peers/peer0.chemistry.universitymvp.com/tls:/etc/hyperledger/fabric/tls
      - peer0chemistryuniversitymvpcom:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 11051:11051
    networks:
      universitymvp:
        aliases:
          - peer0.chemistry.universitymvp.com
