version: "3"

networks:
  universitymvp:
    external:
      name: universitymvp
services:
  nodeapp:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    image: aditya/node-app:latest
    ports:
      - 4000:4000
    networks:
      universitymvp:
        aliases:
          - nodeapp
